feat: change help info logic && update exit code

diff --git a/dockerSH b/dockerSH
--- a/dockerSH
+++ b/dockerSH
@@ -69,7 +69,7 @@ up_one()
     fi
 
     echo -e "$option $option/docker-compose.yml file does not exist"
-    exit 0
+    exit 1
 }
 
 up_common_start()
@@ -77,7 +77,7 @@ up_common_start()
     case "$option" in
       "" )
           echo -e "Please enter a container name\n"
-          exit 0
+          exit 1
           ;;
       * )
           up_one
@@ -108,12 +108,10 @@ y_or_n_three_times()
 
 if [ $# -gt 2 ]
 then
-    echo -e "Too many parameters\n"
-    help_info
-    exit 0
+    echo -e "Too many parameters. See 'dockerSH -h'\n"
+    exit 1
 elif [ $# -lt 1 ]
 then
-    echo -e "No parameters\n"
     help_info
     exit 0
 fi
@@ -185,7 +183,7 @@ case "$1" in
       help_info
       ;;
   * )
-      echo -e "Error command\n"
-      help_info
+      echo -e "Error command. See 'dockerSH -h'\n"
+      exit 1
       ;;
 esac
